name = "CalibrationTests"
uuid = "2818745e-0823-50c7-bc2d-405ac343d48b"
authors = ["David Widmann <dev+git@devmotion.de>"]
version = "0.1.0"

[deps]
CalibrationErrors = "33913031-fe46-5864-950f-100836f47845"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
CalibrationErrors = "0.1"
HypothesisTests = "0.8"
Parameters = "0.12"
StatsBase = "0.32"
StatsFuns = "0.8, 0.9"
julia = "1.1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributions", "SafeTestsets", "Test"]
